#!/bin/bash

# Make sure we are in the right directory
cd $(dirname $0)

# Build the build container
./build_build_sif $1

# Enter the rpms directory and execute the container to dump the packages
cd ./rpms
../images/build/slurm-build-${1}.sif
