#!/bin/bash

# Make sure we are in the right directory
cd $(dirname $0)

# Build the container
./build_img $1

# Enter the build directory and execute the container to dump the packages
cd ./builds
../images/slurm-${1}.img
